spring:
  application:
    name: supermercado-service
  profiles:
    active: prod
  config:
    import: 'vault://, configserver:http://config-server:8888'
  cloud:
    vault:
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
      scheme: ${VAULT_SCHEME:http}
      uri: ${VAULT_SCHEME:http}://${VAULT_HOST:localhost}:${VAULT_PORT:8200}
      token: ${VAULT_TOKEN:hvs.VSlxeCypMevB7HLAYZ1hB73L}
      generic:
        enabled: true
        application-name: supermercado-service
    config:
      username: ${CONFIG_SERVER_USER:config}
      password: ${CONFIG_SERVER_PASS:o5qByEjgPOwh3yXOqf}
  boot:
    admin:
      client:
        url: ${monitoramentoHost}
        username: ${monitoramentoUser}
        password: ${monitoramentoPass}
        instance:
          metadata:
            user:
              name: ${actuatorUser}
              password: ${actuatorPass}

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@